#!/usr/bin/env bash
# Copy the Android Gradle server artifact into HarmonyOS rawfile (byte-for-byte).
# Does not build the server; run Gradle in ../easycontrolnext first.
#
# Remote path on device (ClientStream.java):
#   /data/local/tmp/easycontrolnext_server_<APP_VERSION_CODE>.jar
# where APP_VERSION_CODE is easycontrolnext/app versionCode (not server module versionCode).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANDROID_ROOT="$(cd "$ROOT/../easycontrolnext" && pwd)"
DEST_DIR="$ROOT/entry/src/main/resources/rawfile"
DEST_JAR="$DEST_DIR/easycontrolnext_server.jar"
DEST_META="$DEST_DIR/easycontrolnext_server.version"
APP_GRADLE="$ANDROID_ROOT/app/build.gradle"

# Common Gradle output candidates (first existing wins).
CANDIDATES=(
  "$ANDROID_ROOT/app/src/main/res/raw/easycontrolnext_server.jar"
  "$ANDROID_ROOT/app/src/main/res/raw/easycontrolnext_server"
  "$ANDROID_ROOT/server/build/libs/easycontrolnext_server.jar"
  "$ANDROID_ROOT/server/build/outputs/jar/easycontrolnext_server.jar"
  "$ANDROID_ROOT/server/build/outputs/apk/release/server-release-unsigned.apk"
  "$ANDROID_ROOT/server/build/outputs/apk/debug/server-debug.apk"
)

SRC=""
for c in "${CANDIDATES[@]}"; do
  if [[ -f "$c" ]]; then
    SRC="$c"
    break
  fi
done

if [[ -z "$SRC" ]]; then
  echo "error: server jar not found. Build/copy the Android server module first, e.g.:" >&2
  echo "  (cd \"$ANDROID_ROOT\" && ./gradlew :server:copyRelease)" >&2
  echo "  # or :server:copyDebug" >&2
  echo "Looked for:" >&2
  printf '  %s\n' "${CANDIDATES[@]}" >&2
  exit 1
fi

VERSION_CODE=""
if [[ -f "$APP_GRADLE" ]]; then
  VERSION_CODE="$(
    awk '/defaultConfig[[:space:]]*\{/,/^[[:space:]]*\}/ {
      if ($1 == "versionCode") { print $2; exit }
    }' "$APP_GRADLE" | tr -d '\r'
  )"
fi
if [[ -z "${VERSION_CODE}" ]]; then
  VERSION_CODE="10014"
  echo "warn: could not parse app versionCode; defaulting to ${VERSION_CODE}" >&2
fi

mkdir -p "$DEST_DIR"
cp -f "$SRC" "$DEST_JAR"

HASH="$(shasum -a 256 "$DEST_JAR" | awk '{print $1}')"
SIZE="$(wc -c <"$DEST_JAR" | tr -d ' ')"
REMOTE_NAME="easycontrolnext_server_${VERSION_CODE}.jar"
REMOTE_PATH="/data/local/tmp/${REMOTE_NAME}"
COPIED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat >"$DEST_DIR/easycontrolnext_server.jar.sha256" <<EOF
sha256=$HASH
size=$SIZE
source=$SRC
copied_at=$COPIED_AT
app_version_code=$VERSION_CODE
remote_path=$REMOTE_PATH
EOF

cat >"$DEST_META" <<EOF
# Generated by scripts/copy_server_jar.sh — do not hand-edit.
app_version_code=$VERSION_CODE
remote_name=$REMOTE_NAME
remote_path=$REMOTE_PATH
sha256=$HASH
size=$SIZE
source=$SRC
copied_at=$COPIED_AT
# ClientStream.startServer() also rm's /data/local/tmp/easycontrolnext_* before push when missing/debug.
EOF

# Keep .gitignore in sync: version sidecar is small and useful to commit.
if ! grep -q 'easycontrolnext_server.version' "$ROOT/.gitignore" 2>/dev/null; then
  :
fi

echo "==> copied $SRC"
echo "    -> $DEST_JAR"
echo "    sha256=$HASH size=$SIZE"
echo "    app_version_code=$VERSION_CODE"
echo "    remote_path=$REMOTE_PATH"
echo "note: prefer regenerating via this script over committing large binaries when possible"
